
project_id = "qpveeqvzvukolfagasne"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[functions.analyze-financial-data]
verify_jwt = false

[functions.berget-api-proxy]
verify_jwt = true

[functions.elevenlabs-proxy]
verify_jwt = true

[functions.generate-podcast]
verify_jwt = false
