// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpveeqvzvukolfagasne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwdmVlcXZ6dnVrb2xmYWdhc25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjEzOTcsImV4cCI6MjA2NDY5NzM5N30.rnEQz2aeCFoEPtBGXj6ydg4oKTY8ftX7d4TjrJXMUC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);